#!/bin/bash

cat doing.txt >> tasklist.txt

sed -i '/^$/d' tasklist.txt
shuf tasklist.txt > tasklist_shuf.txt
mv tasklist_shuf.txt tasklist.txt

echo -n "postpone: "
cat doing.txt

head -n 1 tasklist.txt > doing.txt
sed -i '1d' tasklist.txt

echo -n 'next task is: '
cat doing.txt

echo -n "added: remain = "
cat tasklist.txt | wc -l

